/**
 * Created by guangqiang on 2017/8/22.
 */

/**
 * action对象的type属性集合
 */
const actionType = {

  // 配置 promiseMiddleware 异步action的几种状态
  FETCH_LOADING_SUFFIX : '_LOADING',
  FETCH_SUCCESS_SUFFIX : '_SUCCESS',
  FETCH_ERROR_SUFFIX : '_ERROR',

  // action 对象的type
  GET_ACCOUNT_GENERAL : 'GET_ACCOUNT_GENERAL',
  OPEN_CHAT : 'OPEN_CHAT',
  CHAT_INCREASES : 'CHAT_INCREASES',
  CHAT_REDUCE : 'CHAT_REDUCE',

  PICTURE_LIST: 'PICTURE_LIST',
  PICTURE_DETAIL: 'PICTURE_DETAIL',
  PICTURE_PAST_LIST: 'PICTURE_PAST_LIST',
  PICTURE_GRID_LIST: 'PICTURE_GRID_LIST',

  MOVIE_LIST: 'MOVIE_LIST',
  MOVIE_DETAIL: 'MOVIE_DETAIL',
  MOVIE_STORY: 'MOVIE_STORY',

  MUSIC_ID_LIST: 'MUSIC_ID_LIST',
  MUSIC_DETAIL: 'MUSIC_DETAIL',
  MUSIC_LIST: 'MUSIC_LIST',
  MUSIC_XIAMI_MUSIC: 'MUSIC_XIAMI_MUSIC',
  MUSIC_RESET_MUSIC_INFO: 'MUSIC_RESET_MUSIC_INFO'
}

export default actionType
